ALTER TABLE [dbo].[EmployeeSkill]
    ADD CONSTRAINT [PK_EmployeeSkill_1] PRIMARY KEY CLUSTERED ([IdEmployee] ASC, [IdTechnology] ASC, [IdSkill] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

